# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build & Deploy Budgetation

on:
  workflow_dispatch
env:
  AZURE_WEBAPP_PACKAGE_PATH: 'Budgetation'
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run:  (cd ./Budgetation.App/ClientApp && npm install && cd ../../)

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish Budgetation.API -c Release -o drop/Budgetation.API
        
      - name: Build Angular App
        run:  (cd ./Budgetation.App/ClientApp && npm run build -- --configuration=production && cd ../../)
        
      - name: Publish App
        run: dotnet publish Budgetation.App -c Release -o drop/Budgetation.App

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: drop

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: '.'
          
      - name: Deploy API
        id: deploy-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'budgetation-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.API_PROFILE }}
          package: 'Budgetation.API/.'
          
      - name: Deploy App
        id: deploy-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'budgetation'
          slot-name: 'Production'
          publish-profile: ${{ secrets.APP_PROFILE }}
          package: 'Budgetation.App/.'
