# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - budgetation-api

on:
  workflow_dispatch
env:
  AZURE_WEBAPP_PACKAGE_PATH: 'Budgetation.API'
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/Budgetation.API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/Budgetation.API.csproj -c Release -o drop/${{env.AZURE_WEBAPP_PACKAGE_PATH}} 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: drop/${{env.AZURE_WEBAPP_PACKAGE_PATH}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: 'drop/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'budgetation-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D5D337141D18444C9A574173208E4350 }}
          package: '.'
